---

- name: "install aap1"
  hosts: all
  gather_facts: no

  tasks:
  - name: get tower setup tarball
    uri:
      url: https://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-latest.tar.gz
      creates: ansible-tower-setup-latest.tar.gz
      dest: ansible-tower-setup-latest.tar.gz

  - name: unarchive setup
    unarchive:
      src: ansible-tower-setup-latest.tar.gz
      dest: /home/ec2-user
      remote_src: yes