---
- name: install unzip
  ansible.builtin.package:
    name: unzip
    state: present

- name: get awscli archive
  ansible.builtin.uri:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    creates: "/tmp/awscliv2.zip"
    dest: "/tmp/awscliv2.zip"

- name: unarchive awscli
  ansible.builtin.unarchive:
    src: "/tmp/awscliv2.zip"
    dest: "/tmp"
    remote_src: yes

- name: create aws cred directory
  ansible.builtin.file:
    path: /home/ec2-user/.aws
    state: directory
    mode: '0700'
    owner: ec2-user
    group: ec2-user

- name: create aws credentials
  ansible.builtin.template:
    src: aws_credentials.j2
    dest: "/home/ec2-user/.aws/credentials"

- name: create aws config
  ansible.builtin.template:
    src: aws_config.j2
    dest: "/home/ec2-user/.aws/config"
